"""Discover justification-book PDFs from each service's index pages.

The book list is written to sources/fy{FY}_books.yaml so it can be reviewed and committed, and
so ingestion is reproducible. Book filenames are taken from the index pages, never constructed.
Services whose sites refuse automated downloads are kept as `manual` entries: someone downloads
those books in a browser into data/manual/FY{FY}/<exhibit>/ and adds their URLs to the file.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from html import unescape
from pathlib import Path
from urllib.parse import urljoin

import requests
import yaml

from .config import SOURCES_DIR

USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"
HREF_RE = re.compile(r'href\s*=\s*["\']([^"\']+\.pdf)["\']', re.I)


@dataclass(frozen=True)
class Book:
    exhibit: str      # 'R-2'
    service: str
    url: str
    manual: bool = False


def books_path(fiscal_year: int) -> Path:
    return SOURCES_DIR / f"fy{fiscal_year}_books.yaml"


def load_books(fiscal_year: int, exhibit: str) -> list[Book]:
    path = books_path(fiscal_year)
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text()) or {}
    return [
        Book(exhibit, b["service"], b["url"], bool(b.get("manual")))
        for b in (data.get("books") or {}).get(exhibit, [])
        if b.get("url")
    ]


def _links(index_url: str, patterns: list[str]) -> list[str]:
    resp = requests.get(index_url, timeout=60, headers={"User-Agent": USER_AGENT})
    resp.raise_for_status()
    seen, out = set(), []
    for href in HREF_RE.findall(resp.text):
        url = urljoin(resp.url, unescape(href).strip())
        if any(p in url for p in patterns) and url not in seen:
            seen.add(url)
            out.append(url)
    return out


def discover_books(fiscal_year: int) -> tuple[dict[str, list[dict]], list[str]]:
    """Returns ({exhibit: [book entries]}, notes). Manual entries already in the books file are
    kept, so re-running discovery does not drop URLs someone added by hand."""
    sources = yaml.safe_load((SOURCES_DIR / f"fy{fiscal_year}.yaml").read_text())
    existing = {}
    if books_path(fiscal_year).exists():
        existing = (yaml.safe_load(books_path(fiscal_year).read_text()) or {}).get("books") or {}

    books: dict[str, list[dict]] = {}
    notes: list[str] = []
    for exhibit, indexes in (sources.get("justification_indexes") or {}).items():
        entries = books.setdefault(exhibit, [])
        for idx in indexes:
            service = idx["service"]
            if idx.get("manual"):
                kept = [b for b in existing.get(exhibit, []) if b.get("service") == service and b.get("url")]
                entries.extend(kept)
                notes.append(f"{exhibit} {service}: manual ({len(kept)} book(s) listed); index {idx['index']}")
                continue
            patterns = idx["link_contains"]
            patterns = [patterns] if isinstance(patterns, str) else list(patterns)
            try:
                urls = _links(idx["index"], patterns)
            except requests.RequestException as e:
                notes.append(f"{exhibit} {service}: index fetch failed ({e}); nothing listed")
                continue
            entries.extend({"service": service, "url": u} for u in urls)
            notes.append(f"{exhibit} {service}: {len(urls)} book(s) from {idx['index']}")
    return books, notes


def write_books(fiscal_year: int, books: dict[str, list[dict]], notes: list[str]) -> Path:
    path = books_path(fiscal_year)
    header = (
        f"# Generated by `budget discover-books --fy {fiscal_year}` on {date.today().isoformat()} from\n"
        f"# the justification_indexes in fy{fiscal_year}.yaml. Review before ingesting. Manual entries\n"
        f"# (`manual: true`) are kept on re-discovery: add their URLs here and put the downloaded\n"
        f"# PDFs, under the same file name, in data/manual/FY{fiscal_year}/<exhibit>/.\n"
        + "".join(f"#   {n}\n" for n in notes)
    )
    body = yaml.safe_dump({"fiscal_year": fiscal_year, "books": books}, sort_keys=False, width=200)
    path.write_text(header + body)
    return path
